[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "setuptools_scm_azure_pipelines>=0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "llmsearch"
description = "LLM Powered Search Tool"
# version = "0.1.0"
dynamic = ["dependencies", "version"]

[project.optional-dependencies]
dev = [
    "black",
    "pytest",
    "pytest-cov",
    "ruff"
]

[tool.setuptools_scm]
write_to = "src/llmsearch/_version.py"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
dependencies = {file = ["conda_requirements.txt"]}


[tool.ruff]
# Decrease the maximum line length to 79 characters.
line-length = 119
src = ["src"]

[project.scripts]
llmsearch = 'llmsearch.cli:main_cli'
llmsearchapi = 'llmsearch.api:main'